// <auto-generated />
using AlbumBank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlbumBank.Migrations
{
    [DbContext(typeof(AlbumBankContext))]
    partial class AlbumBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("AlbumBank.Models.AlbumItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AlbumTitle");

                    b.Property<string>("AlbumArtist");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Length");

                    b.Property<int>("Tracks");

                    b.HasKey("Id");

                    b.ToTable("AlbumItem");
                });
#pragma warning restore 612, 618
        }
    }
}
